### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by LucaCerullo1** [hzjken/crypto-arbitrage-framework#10]
PS C:\Users\Luca Cerullo\Desktop\crypto-arbitrage-framework-master> & "C:/Users/Luca Cerullo/AppData/Local/Programs/Python/Python39/python.exe" "c:/Users/Luca Cerullo/Desktop/crypto-arbitrage-framework-master/main.py"
Traceback (most recent call last):
  File "c:\Users\Luca Cerullo\Desktop\crypto-arbitrage-framework-master\main.py", line 35, in <module>
    path_optimizer.find_arbitrage()
  File "c:\Users\Luca Cerullo\Desktop\crypto-arbitrage-framework-master\crypto\path_optimizer.py", line 103, in find_arbitrage   
    self.update_objectives()
  File "c:\Users\Luca Cerullo\Desktop\crypto-arbitrage-framework-master\crypto\path_optimizer.py", line 279, in update_objectives
    self.update_transit_price()
  File "c:\Users\Luca Cerullo\Desktop\crypto-arbitrage-framework-master\crypto\path_optimizer.py", line 167, in update_transit_price       
    self.price.update(exc_price)
TypeError: 'NoneType' object is not iterable
PS C:\Users\Luca Cerullo\Desktop\crypto-arbitrage-framework-master> 

I have installed all library but when add exchange API Binance and Coinbase-pro program give me this error

**Comment by hzjken** [comment]
this issue seems like due to below function is returning None value:
https://github.com/hzjken/crypto-arbitrage-framework/blob/882049565d92bdab0c79da95ffe353594b6cc89c/crypto/path_optimizer.py#L378-L389

You might need to have a check on this function using specific exchange names, it's possible that some of the exchanges in ccxt do not support **fetch_tickers** function. I believe Binance do support, Coinbase-pro I am not sure.
