### ISSUE TITLE
Problem starting the bot

### ISSUE THREAD

**Issue by SparkySparkman** [hzjken/crypto-arbitrage-framework#22]
crypto-arbitrage-framework-hzjken$ python3.9 main.py
/home/sparky/Lataukset/Binance-Crypto/Crypto-Arbitrage/crypto-arbitrage-framework-hzjken/path_optimizer.py:241: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  self.commission_matrix[np.meshgrid(indexes, indexes, indexing='ij', sparse=True)] = self.trading_fee[exc_name]
Traceback (most recent call last):
  File "/home/sparky/Lataukset/Binance-Crypto/Crypto-Arbitrage/crypto-arbitrage-framework-hzjken/main.py", line 47, in <module>
    path_optimizer.find_arbitrage()
  File "/home/sparky/Lataukset/Binance-Crypto/Crypto-Arbitrage/crypto-arbitrage-framework-hzjken/path_optimizer.py", line 101, in find_arbitrage
    self.update_commission_fee()
  File "/home/sparky/Lataukset/Binance-Crypto/Crypto-Arbitrage/crypto-arbitrage-framework-hzjken/path_optimizer.py", line 241, in update_commission_fee
    self.commission_matrix[np.meshgrid(indexes, indexes, indexing='ij', sparse=True)] = self.trading_fee[exc_name]
IndexError: arrays used as indices must be of integer (or boolean) type

**Comment by SparkySparkman** [comment]
crypto-arbitrage-framework-hzjken/path_optimizer.py", line 241, in update_commission_fee
    self.commission_matrix[np.meshgrid(indexes, indexes, indexing='ij', sparse=True)] = self.trading_fee[exc_name]
IndexError: arrays used as indices must be of integer (or boolean) type
