### ISSUE TITLE
Problem with update_commission_fee()

### ISSUE THREAD

**Issue by myroom** [hzjken/crypto-arbitrage-framework#26]
Hello 

There is an error when starting, what could be the problem?

path_optimizer.py:241: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  self.commission_matrix[np.meshgrid(indexes, indexes, indexing='ij', sparse=True)] = self.trading_fee[
Traceback (most recent call last):
  File "main.py", line 40, in <module>
    path_optimizer.find_arbitrage()
  File "path_optimizer.py", line 101, in find_arbitrage
    self.update_commission_fee()
  File "path_optimizer.py", line 241, in update_commission_fee
    self.commission_matrix[np.meshgrid(indexes, indexes, indexing='ij', sparse=True)] = self.trading_fee[
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

Process finished with exit code 1

**Comment by myroom** [comment]
![image](https://user-images.githubusercontent.com/5454513/189069502-fd1a0a06-6716-4bdf-a61b-9d737b732325.png)

**Comment by mrdjehknhc** [comment]
same issue , did you find solution ?

**Comment by OPAYA** [comment]
you should use a 0 index .
self.commission_matrix[np.meshgrid(indexes, indexes, indexing='ij', sparse=True)[0]] = self.trading_fee[exc_name]
