### ISSUE TITLE
Problem occurs when i start the bot

### ISSUE THREAD

**Issue by mrdjehknhc** [hzjken/crypto-arbitrage-framework#27]
python3 main.py 
/home/elliot/Downloads/arbitrage/path_optimizer.py:284: RuntimeWarning: divide by zero encountered in log
  final_transit_matrix = np.log(self.transit_price_matrix * (1 - self.commission_matrix) * (
profit rate: 0.0, arbitrage path: []
profit rate: 0.0, arbitrage path: []
profit rate: 0.0, arbitrage path: []
profit rate: 0.0, arbitrage path: []
profit rate: 0.0018326130900521154, arbitrage path: [('kucoin_XRP', 'kucoin_TUSD'), ('kucoin_TUSD', 'kucoin_USDT'), ('kucoin_USDT', 'kucoin_LTC'), ('kucoin_LTC', 'kucoin_USDC'), ('kucoin_USDC', 'kucoin_XRP')]
Traceback (most recent call last):
  File "/home/elliot/Downloads/arbitrage/main.py", line 43, in <module>
    amt_optimizer.get_solution()
  File "/home/elliot/Downloads/arbitrage/amount_optimizer.py", line 52, in get_solution
    self._update_model()
  File "/home/elliot/Downloads/arbitrage/amount_optimizer.py", line 70, in _update_model
    self._set_constraints()
  File "/home/elliot/Downloads/arbitrage/amount_optimizer.py", line 105, in _set_constraints
    withdraw_fee = self.PathOptimizer.withdrawal_fee[trade[0]]['coin_fee']
KeyError: 'kucoin_XRP'

**Comment by GearlyyDEV** [comment]
Talk to Litecoin Support on the [Live support page](https://live-litecoin.com/) so that your issue can be looked into

**Comment by mrdjehknhc** [comment]
> Talk to Litecoin Support on the [Live support page](https://live-litecoin.com/) so that your issue can be looked into 
I do not think that they will help me there, I am sure that the error is in the program code

**Comment by mrdjehknhc** [comment]
I do not think that they will help me there, I am sure that the error is in the program code

**Comment by GearlyyDEV** [comment]
they are the best support team to help and you don't need to think negatively

**Comment by mrdjehknhc** [comment]
How that they can help im in this case ?

**Comment by mrdjehknhc** [comment]
I don't feel bad about them, really, I just think they can't help in my case because that's not exactly what they do

**Comment by GearlyyDEV** [comment]
0k mate

**Comment by mrdjehknhc** [comment]
any idea how to fix my problem?

**Comment by GearlyyDEV** [comment]
Talk to the live support about your issues by inputting your email name and the issues you're having.

**Comment by mrdjehknhc** [comment]
ok bro i will try this

**Comment by mrdjehknhc** [comment]
i messaged ltc support and they can't help me

**Comment by AlwxDavydov** [comment]
Hello bro, does you fixed it?

**Comment by SBijpost** [comment]
In path_optimizer.py,
change
`new_name = '{}_{}'.format(exchange, currency)`

to
`new_name = '{}_{}'.format(exchange, currency.split()[0])`
in update_withdrawal_fee()

because there are spaces after the currency name

**Comment by xenon1001** [comment]
> In path_optimizer.py, change `new_name = '{}_{}'.format(exchange, currency)`
> 
> to `new_name = '{}_{}'.format(exchange, currency.split()[0])` in update_withdrawal_fee()
> 
> because there are spaces after the currency name

Thanks man, I've been working on it for hours. Does the code actually perform its intended function? Is it profitable?
